---
# tasks file for osp-facts

- include_vars: "../../osp-setup/defaults/main.yml"
  tags: set_server_fact

- name: fetch facts for specific instances
  os_server_facts :
    cloud: "{{ cloud_name }}"
    region_name: "{{ region_name }}"
    server: "{{ instance_name }}"
  when: instance_name is defined
  register: frontend_instance
  tags: set_server_fact

- name: fetch facts for all the instances
  os_server_facts :
    cloud: "{{ cloud_name }}"
    region_name: "{{ region_name }}"
  register: instances

- name: add host to group
  add_host:
    name: "{{ item.name }}"
    group: "{{ item.metadata.group }}"
    ansible_host: "{{ item.public_v4 }}"
    ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    ansible_user: "{{ ssh_user }}"
  with_items: "{{ instances.ansible_facts.openstack_servers }}"

- name: launch instances
  os_server_action:
    cloud: "{{ cloud_name }}"
    server: "{{ hostvars[item].inventory_hostname }}"
    action: start
    wait: true
    timeout: 120
  with_inventory_hostnames: frontends:apps:appdbs
