- name: Job template for OSP Instances
  command: |
    tower-cli job_template create --name "{{job_template_name_osp_instances}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{osp_instances_playbook}}" --credential "{{ssh_cred_name}}"

- name: Associate IG to OSP instances job template 
  command: |
    tower-cli job_template associate_ig --job_template "{{job_template_name_osp_instances}}" --instance_group "{{instance_group_name}}"


- name: Create vault credential
  command: |
    tower-cli credential create --name="yum-repo-cred" --organization "{{org_name}}" --inputs='{"vault_password":"ansible"}'  --credential-type="Vault"

- name: Job template for 3tier app deploy on QA Env
  command: |
    tower-cli job_template create --name "{{job_template_name_3tier_app}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{app_deploy_playbook}}" --credential "{{ssh_cred_name}}" --vault-credential "yum-repo-cred"

- name: Associate IG to 3tier job template  
  command: |
    tower-cli job_template associate_ig --job_template "{{job_template_name_3tier_app}}" --instance_group "{{instance_group_name}}"


- name: Job template to delete OSP Instances
  command: |
    tower-cli job_template create --name "{{job_template_name_osp_instances_delete}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{osp_instances_delete_playbook}}" --credential "{{ssh_cred_name}}"

- name: Associate IG to OSP Delete instances job template 
  command: |
    tower-cli job_template associate_ig --job_template "{{job_template_name_osp_instances_delete}}" --instance_group "{{instance_group_name}}"


- name: Job template for smoke test osp instances
  command: |
    tower-cli job_template create --name "{{job_template_smoke_osp}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{osp_smoke_playbook}}" --credential "{{ssh_cred_name}}"

- name: Associate IG to Smoke test job template 
  command: |
    tower-cli job_template associate_ig --job_template "{{job_template_smoke_osp}}" --instance_group "{{instance_group_name}}"

- name: Job template for Provisioning AWS env
  command: |
    tower-cli job_template create --name "{{job_template_aws_provision}}" --job-type run --inventory "{{static_inventory_name}}" --project "{{proj_name}}" --playbook "{{aws_provision_playbook}}" --credential "{{ssh_cred_name}}" --extra-vars @/tmp/aws_jq_vars.yml

- name: Job template for injecting AWS SSH keys
  command: |
    tower-cli job_template create --name "{{job_template_aws_ssh_keys}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{aws_ssh_playbook}}" --credential "{{opentlc_cred_name}}" --extra-vars @/tmp/tower_info.yml

- name: Job template for checking AWS instances status
  command: |
    tower-cli job_template create --name "{{job_template_aws_status_check}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{aws_status_playbook}}" --credential "{{opentlc_cred_name}}"

- name: Job template for 3tier AWS deploy
  command: |
    tower-cli job_template create --name "{{job_template_name_3tier_app_aws}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{app_deploy_playbook}}"  --vault-credential "yum-repo-cred"

- name: Job template for smoke test aws instances
  command: |
    tower-cli job_template create --name "{{job_template_smoke_aws}}" --job-type run --inventory "{{ec2_dynamic_inventory}}" --project "{{proj_name}}" --playbook "{{aws_smoke_app_playbook}}" --vault-credential "yum-repo-cred"
